### ISSUE TITLE
'strathweb_phi_engineFFI.h' file not found

### ISSUE THREAD

**Issue by ktmobility1** [filipw/strathweb-phi-engine#24]
When building swift, an error occurs saying that strathweb_phi_engineFFI.h does not exist. Why is that? I followed it exactly, but can I find out the cause?

**Comment by filipw** [comment]
what exactly do you invoke (and from which folder, maybe it's a relative path issue). If you see [here](https://github.com/filipw/strathweb-phi-engine/blob/main/.github/workflows/ci.yml#L49-L69) the CI build just runs `build-swift.sh` and that builds the Swift Package.

This should then be enough to go to the samples, to the iOS app and build it in Xcode (it references the locally built Swift Package).
